Refactored ValuesAverageExpectationParser to sum and count
MarquezProject/marquez pull request #1353
Opened 2021-05-24 23:34 UTC by collado-mike

For parsing and displaying metrics, I think collecting count and sum separately is more versatile and useful than just reporting average. Average is easy to compute from count and sum, but it's impossible to go the other way.

2021-05-25 13:23 UTC, mobuchowski commented
The change makes sense. You need to update `ColumnMetric` definition as well - now it does not expect `sum` to be there.

2021-05-25 13:24 UTC, mobuchowski requested changes
The change makes sense. Though, you need to update ColumnMetric definition as well - now it does not expect sum to be there.

2021-05-27 09:35 UTC, mobuchowski approved these changes

2021-05-27 23:18 UTC, merged

2021-05-27 23:19 UTC, wslulciuc reviewed
LGTM 👍