add code of conduct 2.0 [https://github.com/MarquezProject/marquez/is…
MarquezProject/marquez pull request #852
Opened 2020-11-29 10:04 UTC by sreev

…sues/850]

Signed-off-by: Sree Vaddi <441385+sreev@users.noreply.github.com>

2020-11-29 16:52 UTC, wslulciuc commented on README.md
> +## Code of Conduct
With the contributor covenant badge added to our _Badges_ section, this section can be removed.

2020-11-29 16:54 UTC, wslulciuc requested changes
This looks good, I'd remove the _Code of Conduct_ (in the README.md) as we already link out to the contributor covenant via the badge. The section would make more sense to be added to our [CONTRIBUTING.md](https://github.com/MarquezProject/marquez/blob/main/CONTRIBUTING.md)

2020-11-29 18:02 UTC, sreev commented
code of conduct should and must be the first read.

2020-11-29 18:21 UTC, wslulciuc commented
> We recommend that you add the Markdown or text version of the Contributor Covenant to your source code repository at the root level.

They just recommend we add the text to the root of our repo, which we are with [CODE_OF_CONDUCT.md](https://github.com/MarquezProject/marquez/blob/main/CODE_OF_CONDUCT.md). Am I missing something?

2020-11-30 21:36 UTC, julienledem requested changes
Thanks for updating the code of conduct to the latest version.
Please adress my comment bellow so that we can merge.

2020-11-30 21:36 UTC, julienledem commented on README.md
> +Instructions for translations can be found [here](https://github.com/ContributorCovenant/contributor_covenant#translating).
I don't think this section is relevant to the Marquez README.
Having the badge and CODE_OF_CONDUCT.md at the root of the repo is sufficient.

2020-12-08 06:37 UTC, wslulciuc commented
Closing as this code of conduct has been updated.

2020-12-08 06:37 UTC, closed without merging